"""Insight engine for retrieving pre-processed ad performance insights and brand USPs."""
from backend.app.core.database import get_firestore


def retrieve_ad_insights(hotel_name: str) -> dict:
    """Retrieve pre-processed ad performance insights for a hotel from Firestore.

    Insights are generated by Gemini when a historical ads CSV is uploaded.
    Falls back to a global insight doc if no hotel-specific insights exist.
    Returns empty dict if no insights are available at all.
    """
    db = get_firestore()

    # Try hotel-specific insights first
    docs = list(
        db.collection("ad_insights")
        .where("hotel_name", "==", hotel_name)
        .limit(1)
        .stream()
    )
    if docs:
        return docs[0].to_dict()

    # Fallback: try global insights (generated across all hotels)
    global_docs = list(
        db.collection("ad_insights")
        .where("hotel_name", "==", "_global")
        .limit(1)
        .stream()
    )
    if global_docs:
        return global_docs[0].to_dict()

    return {}


def get_brand_usps(hotel_name: str) -> dict | None:
    """Retrieve brand USP data for a hotel from Firestore."""
    db = get_firestore()
    docs = list(
        db.collection("brand_usps").where("hotel_name", "==", hotel_name).limit(1).stream()
    )
    if docs:
        return docs[0].to_dict()
    return None
